[package]
name = "psutil"
version = "3.1.0"
authors = ["Caleb Bassi <calebjbassi@gmail.com>", "Rob Day <rkd@rkd.me.uk>", "Sam Clements <sam@borntyping.co.uk>"]
description = "Process and system monitoring library"
repository = "https://github.com/rust-psutil/rust-psutil"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
cfg-if = "0.1.10"
once_cell = "1.2.0"
snafu = "0.6.0"

derive_more = { version = "0.99.2", optional = true, default-features = false, features = ["add", "sum"]}
glob = { version = "0.3.0", optional = true }
num_cpus = { version = "1.11.1", optional = true }
platforms = { version = "0.2.1", optional = true }
renamed_serde = { version = "1.0", optional = true, package = "serde", features = ["derive"] }
signal = { version = "0.7.0", optional = true }
unescape = { version = "0.1.0", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
darwin-libproc = { version = "0.1.1", optional = true }
mach = { version = "0.3.2", optional = true }

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.17.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["winbase", "handleapi", "errhandlingapi", "processthreadsapi", "winerror", "sysinfoapi", "fileapi", "winioctl", "ioapiset", "iptypes", "iphlpapi", "netioapi", "winreg", "psapi", "synchapi", "memoryapi", "shellapi", "wow64apiset", "basetsd"] }
ntapi = "0.3.4"

[target.'cfg(all(target_os = "windows", target_pointer_width = "32"))'.dependencies]
ctor = "0.1.15"

[features]
default = ["cpu", "disk", "host", "memory", "network", "process", "sensors"]
serde = ["renamed_serde", "platforms/serde"]

# Modules
cpu = ["mach", "num_cpus"]
disk = ["derive_more", "unescape"]
host = ["platforms"]
memory = ["mach"]
network = ["derive_more"]
process = ["darwin-libproc", "mach", "memory"]
sensors = ["glob"]

[dev-dependencies]
float-cmp = "0.6.0"
chrono = "0.4.13"
